apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-tarea-4-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-web
  template:
    metadata:
      labels:
        app: test-web
    spec:
      containers:
        - image: nginx
          name: contenedor-nginx
