apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-guestbook
  labels:
    app: guestbook
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - image: iesgn/guestbook
          name: contenedor-guestbook
          ports:
            - name: http
              containerPort: 5000
